server:
  port: 8082
spring:
  data:
    mongodb:
      database: eagleeye-vehicleDb
      host: ${MONGO:localhost}
      port: 27017

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: vehicle-service
    instance-id: ${eureka.instance.hostname} - ${random.value}
