server:
  port: 8083
spring:
  data:
    mongodb:
      host: ${USER_VEHICLE_DB:localhost}
      database: eagleeye_userVehicle_db
      port: 27017
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: userVehicle-service
    instance-id: ${eureka.instance.hostname}:${random.long}

