server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/license-service
    password: password
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

message:
  for:
    me: "whats up dude!"
