eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA:http://localhost:8761/}
server:
  port: 8081
spring:
  data:
    mongodb:
      host: ${USERDB_HOST:localhost}
      port: 27017
      database: eagleeye-userdb
  
